# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Gen-Z bus specific drivers.

genz-y := genz-core.o \
          genz-types.o \
          genz-sysfs.o \
          genz-control.o 

obj-$(CONFIG_GENZ)           += genz.o

